(ffi:require js:fs "fs")

(defun test (filename)
  (with-open-file (in filename)
    (let ((eof-value '#:eof)
          (fail-forms '())
          (error-forms '()))
      (do ((form (read in nil eof-value) (read in nil eof-value)))
          ((eq form eof-value))
        (prin1 form)
        (terpri)
        (handler-case
            (eval form)
          (error (e)
            (push form error-forms)
            (format t "*** ERROR ***: ~A~%" e))
          (:no-error (ok)
            (if ok
                (write-line "OK")
                (progn
                  (push form fail-forms)
                  (write-line "FAIL"))))))
      (terpri)
      (terpri)
      (write-line "==================== FAIL FORMS ====================")
      (dolist (form (nreverse fail-forms))
        (prin1 form)
        (terpri))
      (terpri)
      (write-line "==================== ERROR FORMS ====================")
      (dolist (form (nreverse error-forms))
        (prin1 form)
        (terpri)))))

(test "sacla-tests/must-symbol.lisp")
(test "sacla-tests/must-cons.lisp")
(test "sacla-tests/must-character.lisp")
(test "sacla-tests/must-string.lisp")
(test "sacla-tests/must-sequence.lisp")
(test "sacla-tests/must-condition.lisp")
